---
title: "Data Loading and wrangling"
output:
  pdf_document: default
urlcolor: blue
---

```{r}
library(rvest)
library(tidyverse)
library(readxl)
library(janitor)
library(stringr)
library(lubridate)
library(glue)
```


Data scraping wikipedia

```{r}
link <- read_html("https://en.wikipedia.org/wiki/List_of_dams_and_reservoirs_in_Maharashtra")
daminfo <- html_node(link, 'table') %>%
  html_table(fill = TRUE)
```


loading 2015 data

```{r}
dam2015 <- read_excel("Data/2015.xlsx") %>%
  clean_names() %>%
  pivot_longer(cols = c(-reservoir_name, -district, -basin),
               names_to = "month") %>%
  mutate(day = 1) %>%
  separate(month, into = c("month", "year"), sep = "_") %>%
  mutate(month = case_when(
    month == "jan" ~ 1,
    month == "feb" ~ 2,
    month == "mar" ~ 3,
    month == "apr" ~ 4,
    month == "may" ~ 5,
    month == "jun" ~ 6,
    month == "jul" ~ 7,
    month == "aug" ~ 8,
    month == "sep" ~ 9,
    month == "oct" ~ 10,
    month == "nov" ~ 11,
    month == "dec" ~ 12),
    date = make_date(year, month, day),
    storage_bcm = as.numeric(value)) %>%
  select(reservoir_name, district, basin, date, value, month, day, year)
  

daminfo <- daminfo %>%
  clean_names() %>%
  mutate(name_of_dam = case_when(
    name_of_dam == "Koyna" ~ "Koyana/Shivaji Sagar",
    name_of_dam == "Hatnur" ~ "Upper TapiHatnur Reservoir",
    name_of_dam == "Isapur" ~ "Isapur Reservoir",
    name_of_dam == "Upper Vaitarana" ~ "Upper Vaitarana Reservoir",
    name_of_dam == "Khadakwasla" ~ "Khadakwasla Reservoir",
    name_of_dam == "Yeldari" ~ "Yeldari Reservoir",
    name_of_dam == "Mula" ~ "Mula Reservoir",
    name_of_dam == "Jayakwadi" ~ "JayakwadiNath Sagar",
    name_of_dam == "Girna" ~ "Girna Reservoir",
    name_of_dam == "Mulshi" ~ "Mulshi Dam",
    name_of_dam == "Kanher" ~ "Kanher Dam",
    name_of_dam == "Ujani" ~ "BhimaUjjani Reservoir",
    TRUE ~ name_of_dam
  ) )

dam2015fin <- left_join(dam2015, daminfo, by = c ("reservoir_name" = "name_of_dam")) %>%
  mutate(gross_storage_capacity_103m3 = as.numeric(gross_storage_capacity_103m3),
         effective_storage_capacity_103m3 = as.numeric(effective_storage_capacity_103m3),
         value = as.numeric(value)) %>%
  select(-na)


#make factors for graph
dam2015fin2 <- dam2015fin %>%
  drop_na() %>%
  mutate(purpose = str_replace(purpose, "  ", " & "),
         purpose = fct_relevel(purpose, c("Hydroelectricity",
                                          "Irrigation",
                                          "Irrigation & Hydroelectricity",
                                          "Irrigation & Water supply")))
```


2015 wide format

```{r}
wide2015 <- dam2015fin %>%
  select(-month, -day, -year) %>%
  pivot_wider(names_from = date, values_from = value)
```


```{r}
cruncher<- function(data){
  read_excel(data, col_types = c("text", 
    "text", "text", "text", "text", 
    "text", "text", "text", "text", 
    "text", "text", "text", "text", 
    "text", "text")) %>%
  clean_names() %>%
  pivot_longer(cols = c(-reservoir_name, -district, -basin),
               names_to = "month") %>%
  mutate(day = 1) %>%
  separate(month, into = c("month", "year"), sep = "_") %>%
  mutate(month = case_when(
    month == "jan" ~ 1,
    month == "feb" ~ 2,
    month == "mar" ~ 3,
    month == "apr" ~ 4,
    month == "may" ~ 5,
    month == "jun" ~ 6,
    month == "jul" ~ 7,
    month == "aug" ~ 8,
    month == "sep" ~ 9,
    month == "oct" ~ 10,
    month == "nov" ~ 11,
    month == "dec" ~ 12),
    date = make_date(year, month, day),
    storage_bcm = as.numeric(value)) %>%
  select(reservoir_name, district, basin, date, storage_bcm, month, day, year)
}

year <- 2015:2020 
dataglue <- glue("Data/{year}.xlsx")
dataname <- glue("dam{year}")


dam2015 <- cruncher("Data/2015.xlsx")
dam2016 <- cruncher("Data/2016.xlsx")
dam2017 <- cruncher("Data/2017.xlsx")
dam2018 <- cruncher("Data/2018.xlsx")
dam2019 <- cruncher("Data/2019.xlsx")
dam2020 <- cruncher("Data/2020.xlsx")


# for(i in 1:length(dataglue)){
#   dataname[i] <- cruncher(dataglue[i])
# }

bigdata <- bind_rows(dam2015, dam2016, dam2017, dam2018, dam2019, dam2020)

biggerdata <- inner_join(bigdata, daminfo, by = c ("reservoir_name" = "name_of_dam")) %>%
  mutate(gross_storage_capacity_109m3 = as.numeric(gross_storage_capacity_103m3)/1000000,
         effective_storage_capacity_109m3 = as.numeric(effective_storage_capacity_103m3)/1000000) %>%
  select(-na) %>%
  mutate(purpose = str_replace(purpose, "  ", " & "),
         purpose = fct_relevel(purpose, c("Hydroelectricity",
                                          "Irrigation",
                                          "Irrigation & Hydroelectricity",
                                          "Irrigation & Water supply")))


write_csv(biggerdata, here("damdata.csv"))
```

